title: Rogers Executive Workshop 3
email: rboutaba@uwaterloo.ca
description: >-
  Transport Network Programmability — the third workshop in the Rogers Executive Workshop Series,
  presented as part of the Rogers Chair in Network Automation at the University of Waterloo.
baseurl: "/rogers-workshop-3"
url: "https://niloysh.github.io"
author: Raouf Boutaba

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: classic
  social_links: []